version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: global_task_fintech_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=global_task_fintech_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: global_task_fintech:latest
    container_name: global_task_fintech_app
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PHX_HOST=localhost
      - PORT=4000
      - PHX_SERVER=true
      - DATABASE_URL=ecto://postgres:password@db/global_task_fintech_dev
      - BUSINESS_RULES_BASE_URL=http://gorules:8080
    depends_on:
      db:
        condition: service_healthy
      gorules:
        condition: service_started


  gorules:
    build: ./gorules
    container_name: gorules-engine
    ports:
      - "${GORULES_PORT:-9080}:8080"
    volumes:
      - ./gorules/rules:/app/rules
    environment:
      - PORT=8080
      - RULES_DIR=/app/rules
    restart: always

volumes:
  postgres_data:
