apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: global-task-fintech
type: Opaque
stringData:
  SECRET_KEY: "uE/qX/mKqD9pB0+vT+vM0v3wZ+UvW+zZ0v++xZ+zZ0v++xZ+vT+vM0v3wZ+UvW+zZ0v++xZ+zZ=="
  ENCRYPTION_KEY: "nALcGiCLivUdDH/jYUpjZFy1D98USXj/ZV7sKx05ETk="
  DATABASE_URL: "ecto://postgres:password@postgres-service:5432/global_task_fintech_prod"
  WEBHOOK_STATUS_UPDATE_URL: "https://webhook.site/04e04c06-bd8f-4529-918e-97206cac1eab"
